#ifndef TABLE_H
#define TABLE_H

int trans_table[18][20] = 
{/*	L |  D | . | ESPAÇO | TAB | \n |"*//* | _ | EOF | { | } | < | - | OP_R | OP_A | ( | ) | ; | E | OUTRO |*/
/*init*/ ID, INT, ERROR, _init_, END, _init_, STR, ERROR, _eof_, COMMENT, ERROR, _ATRIB_, ARITM, OPER, ARITM, AB_P, FC_P, PT_V, ID, ERROR,
/*ID*/	ID, ID, ERROR, END, END, END, ERROR, ID, _eof_, COMMENT, ERROR, END, END, END, END, END, END, END, ID, ERROR,
/*INT*/ ERROR, INT, _REAL_, END, END, END, ERROR, ERROR, _eof_, COMMENT, ERROR, END, END, END, END, ERROR, END, END, _EXP_, ERROR,
/*_REAL_*/ ERROR, REAL, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
/*REAL*/ ERROR, REAL, ERROR, END, END, END, ERROR, ERROR, _eof_, COMMENT, ERROR, END, END, END, END, ERROR, ERROR, END, _EXP_, ERROR,
/*_EXP_*/ERROR, EXP, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
/*EXP*/ ERROR, EXP, ERROR, END, END, END, END, ERROR, END, END, END, END, END, END, END, AB_P, FC_P, PT_V, ERROR, ERROR,
/*STR*/	STR, STR, STR, STR, STR, STR, END, STR, ERROR, STR, STR, STR, STR, STR, STR, STR, STR, STR, STR, STR,
/*_ATRIB_*/ END, END, ERROR, END, END, END, ERROR, ERROR, _eof_, COMMENT, ERROR, ERROR, ATRIB, END, ERROR, END, END, END, END, ERROR,
/*ATRIB*/ END, END, ERROR, END, END, END, END, ERROR, _eof_, COMMENT, ERROR, ERROR, ERROR, ERROR, ERROR, END, ERROR, END, END, ERROR,
/*OPER*/ END, END, ERROR, END, END, END, ERROR, ERROR, _eof_, COMMENT, ERROR, ERROR, ERROR, OPER, ERROR, END, ERROR, END, END, ERROR,
/*ARITM*/ END, END, ERROR, END, END, END, ERROR, ERROR, _eof_, COMMENT, ERROR, ERROR, ERROR, ERROR, ERROR, END, END, END, END, ERROR,
/*COMMENT*/ COMMENT, COMMENT, COMMENT, COMMENT, COMMENT, COMMENT, COMMENT, COMMENT, ERROR, COMMENT, END, COMMENT, COMMENT, COMMENT, COMMENT, COMMENT, COMMENT, COMMENT , COMMENT, COMMENT,
/*ERROR*/ END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END,
/*EOF*/  END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END,
/*ABR_P*/  END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END,
/*FC_P*/  END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END,
/*PT_V*/  END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END, END
};

#endif
